apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sakshi-bookingservice
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
